# Generated by Django 5.2.8 on 2025-11-21 15:56

import apps.incapacities.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incapacity_type', models.CharField(choices=[('EG', 'Enfermedad General'), ('AL', 'Accidente Laboral'), ('AT', 'Accidente de Tránsito'), ('LM', 'Licencia de Maternidad'), ('LP', 'Licencia de Paternidad')], max_length=2)),
                ('diagnosis_code', models.CharField(max_length=10, verbose_name='Código CIE-10')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('days', models.PositiveIntegerField(verbose_name='Días de incapacidad')),
                ('entity_name', models.CharField(max_length=100, verbose_name='EPS o ARL')),
                ('status', models.CharField(choices=[('REPORTED', 'Reportada (Documentos pendientes)'), ('IN_PROCESS', 'En Trámite (Docs Completos)'), ('TRANSCRIBED', 'Transcrita en EPS'), ('AUTHORIZED', 'Autorizada / Cobrada'), ('REJECTED', 'Rechazada por EPS'), ('PAID', 'Pagada'), ('CLOSED', 'Cerrada / Archivada')], default='REPORTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incapacities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncapacityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CERT', 'Certificado Incapacidad'), ('EPI', 'Epicrisis / Historia Clínica'), ('FURIPS', 'Formulario FURIPS (Accidentes)'), ('REG', 'Registro Civil (Paternidad)'), ('ID', 'Copia Cédula'), ('OTH', 'Otro')], max_length=10)),
                ('file', models.FileField(upload_to=apps.incapacities.models.incapacity_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado por RRHH')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('incapacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='incapacities.incapacity')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incapacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incapacities.incapacity')),
            ],
        ),
    ]
