# Generated by Django 5.2.8 on 2025-11-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacity',
            name='ibc_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IBC (Salario Mes)'),
        ),
    ]
