# Generated by Django 5.2.8 on 2025-11-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incapacities', '0002_incapacity_ibc_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pagado')),
                ('payment_date', models.DateField(verbose_name='Fecha del Pago')),
                ('reference_number', models.CharField(max_length=50, verbose_name='Número de Referencia/Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incapacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='incapacities.incapacity')),
            ],
        ),
    ]
